language: java
jdk: oraclejdk8

services:
  - docker
env:
  jobs:
  - SERVICE=./monolithic/ui
  # - SERVICE=./microservice/frontend/catalog
  # - SERVICE=./microservice/service/cart
  # - SERVICE=./microservice/service/product
  # - SERVICE=./microservice/service/product-go
  # - SERVICE=./microservice/service/navigation
  global:
  - JDK_VERSION=8
before_install:
  - docker pull openjdk:${JDK_VERSION}-jdk
script:
  - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp openjdk:${JDK_VERSION}-jdk ./gradlew -p $SERVICE check
