os: linux
dist: trusty
language: java
jdk: 
- oraclejdk8
- oraclejdk9

env:
  - COVERAGE=0.05 SERVICE=./monolithic/ui
  - COVERAGE=0.14 SERVICE=./monolithic/service/cart
  - COVERAGE=0.0 SERVICE=./monolithic/service/user
  - COVERAGE=0.36 SERVICE=./monolithic/repository/order
  - COVERAGE=0.0 SERVICE=./monolithic/repository/cart
  - COVERAGE=0.12 SERVICE=./monolithic/repository/product
  - COVERAGE=0.31 SERVICE=./monolithic/repository/user

services:
  - docker
install:
  - "./gradlew clean jar"
script:
  - ./gradlew -p $SERVICE check
after success:
  - COVERAGE=0.35 ./gradlew test jacocoTestCoverageVerification

after failure:
  - echo "errored"

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true
