os: linux
dist: trusty
language: java
jdk: oraclejdk8

services:
  - docker
install:
  - "./gradlew clean jar"
script:
  - ./gradlew test
after success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
