os: linux
dist: trusty
language: java
jdk: oraclejdk8

services:
  - docker
install:
  - "./gradlew clean jar"
script:
  - ./gradlew test
after success:
  - COVERAGE=0.35 ./gradlew test jacocoTestCoverageVerification

after failure:
  - echo "errored"

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true
